modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1
license="MIT"

[[mods]]
modId="lightsout"
version="1.0.0"
displayName="Lights out"
description="A horror mod that plays with darkness and voice mimicry."
